name: racing
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  vania: ^0.3.0

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  pointycastle: 3.7.3
